language: objective-c
rvm:
  - 2.1.0
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - rvm get stable
  - rvm install 2.1.0
  - rvm use 2.1.0
  - gem install cocoapods -v '0.38.2'
script: rake test:ci analyze
cache: bundler
notifications:
  email: false
