language: objective-c
rvm:
  - 1.9.3
before_install:
  - gem install cocoapods -v '0.38.2'
  - brew update
  - brew unlink xctool
  - brew install xctool
  - rvm get stable
  - rvm install 2.1.0
  - rvm use 2.1.0
script: rake test:ci analyze
cache: bundler
notifications:
  email: false
